### ISSUE TITLE
Testing iRecord on Drupal 11

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#1954]
Testing and tick when OK:
- [ ] Adding records (casual record & list, including with photo)
- [ ] Verification (verify a record, add comment)
- [ ] downloading records
- [ ] my sites (creating and editing)
- [ ] Activities (creating and displaying)
- [ ] setting up a new recording form
- [ ] uploading from spreadsheets
- [ ] Explore pages (my/all records, sites, species pages)
- [ ] Forum pages and posting
- [ ] check for PHP errors
- [ ] styles CSS / page display issue
- [ ] check the apps work
- [ ] help pages viewing correctly

**Comment by kitenetter** [comment]
@BirenRathod results of initial testing are here:

[Drupal 11 testing.docx](https://github.com/user-attachments/files/24945437/Drupal.11.testing.docx)

I'm not sure what needs doing to test the apps?

**Comment by BirenRathod** [comment]
@kitenetter Thanks, I’ll need to look into it and make the necessary changes. As for the app, it mainly needs a check on the communication part, which @kazlauskis has already done, but I’ll double-check with him.

**Comment by BirenRathod** [comment]
@kitenetter I made some changes, but most of the changes should be done at Indicia's iForm module Which @johnvanbreda should be able to do that.

@johnvanbreda The comments in red need to be addressed. 

[Drupal.11.testing_Biren_comments.docx](https://github.com/user-attachments/files/25293038/Drupal.11.testing_Biren_comments.docx)

**Comment by johnvanbreda** [comment]
@BirenRathod when I try to log into the test site, I get this:
```
Drupal\Core\Entity\EntityStorageException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'consumer_field_data.user_id' in 'WHERE': SELECT "base_table"."id" AS "id", "base_table"."id" AS "base_table_id" FROM "consumer" "base_table" INNER JOIN "consumer_field_data" "consumer_field_data" ON "consumer_field_data"."id" = "base_table"."id" WHERE ("consumer_field_data"."user_id" IN (:db_condition_placeholder_0)) AND ("consumer_field_data"."default_langcode" IN (:db_condition_placeholder_1)); Array ( [:db_condition_placeholder_0] => 3 [:db_condition_placeholder_1] => 1 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 815 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

**Comment by BirenRathod** [comment]
@johnvanbreda this is not a major issue, I was removing some data. It won't take long me to resolve this.

**Comment by BirenRathod** [comment]
@johnvanbreda That has been resolved now.

**Comment by BirenRathod** [comment]
@johnvanbreda Regarding PHP 8.4, there are few errors regarding "explicit nullable type" in iForm module. 
See this error
Deprecated: hostsite_cache_get(): Implicitly marking parameter $expireEarlyIfLoggedIn as nullable is deprecated, the explicit nullable type must be used instead in /code/web/modules/custom/iform/iform.hostsite_api.inc on line 846 Deprecated: helper_base::cacheGet(): Implicitly marking parameter $expireEarlyIfLoggedIn as nullable is deprecated, the explicit nullable type must be used instead in /code/web/modules/custom/iform/client_helpers/helper_base.php on line 3541 Deprecated: helper_base::getCachedResponse(): Implicitly marking parameter $expireEarlyIfLoggedIn as nullable is deprecated, the explicit nullable type must be used instead in /code/web/modules/custom/iform/client_helpers/helper_base.php on line 3812

**Comment by johnvanbreda** [comment]
@BirenRathod I've committed 2 JavaScript fixes (see the links above) that should fix the JS errors in the Word document you sent. Please can you deploy them.

I'll have a look at the nullable issues in a moment - they should be not too hard to fix I hope.

**Comment by BirenRathod** [comment]
@johnvanbreda I have applied both patches on dev & test sites.

**Comment by johnvanbreda** [comment]
Thanks. There is another patch in the link above which fixes some of the PHP warnings, and also this one should hopefully fix the rest: 
https://github.com/Indicia-Team/client_helpers/commit/9305f0cddbb01d53abcdae71b5817fa7b614184d

Please can you make sure these patches are applied to the upstream too (though not urgent).

**Comment by BirenRathod** [comment]
@johnvanbreda All patched have been updated on dev & test now.

**Comment by BirenRathod** [comment]
@johnvanbreda I’ve done a quick check and most of the jQuery issues have now been resolved, except for one on this page:
https://test-brc-irecord-d11.pantheonsite.io/irecord-app-info-centre
 — this appears to be related to jqPlot.

I’m also no longer seeing any PHP 8.4–related errors, which suggests that those issues have now been resolved.

@kitenetter — could you please review this and let @johnvanbreda know if any implementation changes are required?

At present, some style-related issues (such as the small grid display on the verification page and similar items) have not yet been implemented, but most of the jQuery-related issues have been fixed.

**Comment by johnvanbreda** [comment]
Hi @BirenRathod there are 2 more commits above which will fix the issue with jqPlot. 

Plus it would be best to deploy this commit for any issues with the scratchpads: https://github.com/Indicia-Team/client_helpers/commit/d3ea1b03f2244c3fbcbf5cf2e86e3306ea3c643b

**Comment by BirenRathod** [comment]
@johnvanbreda Those commits have been updated on both environments.

**Comment by johnvanbreda** [comment]
@BirenRathod Please can you add this CSS to all the verification pages (e.g. in the files/indicia/css/node.x.css files):
```css
#navbar-top, #block-irecord-bootstrap-breadcrumbs {
    display: none;
}
@media (min-width:1200px) {
    #content h1 {
        font-size: 1.5rem;
    }
}
```

I've also changed the Bootstrap mode to Bootstrap 5 on the iForm settings page which improves the layout of table footers and a few other things.

There is still an issue with the verification page not sizing itself correctly, due to the table headers being too tall at the moment the resize operation occurs. I haven't managed to work this out yet.

**Comment by kitenetter** [comment]
@johnvanbreda I think you've already picked up on this, but here is the screenshot I annotated, and that we discussed earlier today:

<img width="2000" height="1091" alt="Image" src="https://github.com/user-attachments/assets/c8916bd8-a8c2-4816-a213-73340d7558e8" />

**Comment by kitenetter** [comment]
@BirenRathod when you log in to the D11 test site, it initially asks for username/email plus password, but does not display a captcha test:

<img width="969" height="614" alt="Image" src="https://github.com/user-attachments/assets/ad8eb7bf-2a61-4074-b465-36ce6e2ae171" />

But when you try to log in, it then complains that the captcha has not been completed, which adds an extra step to the process:

<img width="775" height="647" alt="Image" src="https://github.com/user-attachments/assets/a6192ed2-961d-49aa-be6e-68e276fb2423" />

**Comment by BirenRathod** [comment]
@kitenetter The CAPTCHA warning appears correctly because only the iRecord live domain is configured as a valid URL in the CAPTCHA settings. Therefore, when the site is used on a test or development environment, it should not block users from logging in.

**Comment by BirenRathod** [comment]
> [@BirenRathod](https://github.com/BirenRathod) Please can you add this CSS to all the verification pages (e.g. in the files/indicia/css/node.x.css files):
> 
> #navbar-top, #block-irecord-bootstrap-breadcrumbs {
>     display: none;
> }
> @media (min-width:1200px) {
>     #content h1 {
>         font-size: 1.5rem;
>     }
> }
> I've also changed the Bootstrap mode to Bootstrap 5 on the iForm settings page which improves the layout of table footers and a few other things.
> 
> There is still an issue with the verification page not sizing itself correctly, due to the table headers being too tall at the moment the resize operation occurs. I haven't managed to work this out yet.

@johnvanbreda I implemented all css files on all verification pages.

**Comment by kitenetter** [comment]
Final checks needed before we go live

**Comment by BirenRathod** [comment]
@kitenetter @johnvanbreda @MarkAlliston @robin-hutchinson @kazlauskis  The iRecord D11 test site is ready. We now need to schedule a date for the migration of the D10 site.

**Comment by kitenetter** [comment]
@BirenRathod on all four verification pages the following adjustments are needed in the D11 layout:
- the grid of records needs to be wider, and the map + details section needs to be narrower, to match the spacing on the D10 site
- the font for the "Comments" and "Experience" tabs can be a bit smaller, so that more rows can be displayed

**Comment by BirenRathod** [comment]
@kitenetter That's done.

**Comment by kitenetter** [comment]
**Verification pages**
Width of grid vs map looks fine now, thanks.

Has the font size for the "Comments" and "Experience" tabs changed? Still looks a bit too big to me.

**Occurrence pages**
I would say that there is too much white space, e.g. in this [occurrence page example](https://test-brc-irecord-d11.pantheonsite.io/record-details?occurrence_id=53630849) - I think the rows could be closer together.

Also the heading "Record of Pamponerus germanicus" can be a smaller font.

**Activities list**
Headings for each [Activity](https://test-brc-irecord-d11.pantheonsite.io/activities/list) (i.e. the Activity names) can be a smaller font.

**Comment by BirenRathod** [comment]
The font size used throughout the site is consistent. It is slightly larger than before and is the default size defined by the theme.

I'll see whether reducing it slightly makes a noticeable difference.

**Comment by BirenRathod** [comment]
@kitenetter The font size has been implemented on all pages now.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that looks better to me. I'm not aware of any other concerns for the D11 site, but we should make sure that we have people available to deal with any feedback when the change is made. And it would be good to announce the change in advance of doing it, so can we schedule it in with one or two week's notice?

**Comment by BirenRathod** [comment]
@kitenetter I have no issue with proceeding on that timescale. It should take me approximately half a day to set up the site in D11.
