### ISSUE TITLE
Set up import from iNaturalist

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#525]
Deadline: we need to have this up and running in time for the 2019 City Nature Challenge, which starts on 26 April.

**Action**
Set up iNaturalist importer to bring in iNaturalist records, where:
- they are within the UK
- they have been given research-grade status
- they are at species level or lower (assuming that this option is available - not sure if it was set up in 2018)

Import to include the CC licence for each record.

See #526 for photo licences.

**Questions**
Timing of import:
How long do we leave observations on iNat before importing into iRecord? The longer the time period is the more chance there is of a stable research-grade ID being reached. 
Should we harvest all research grade obs as soon as they reach research-grade, and do we repeatedly trawl for further obs over time? 
What happens if there is subsequent disagreement on an iNat identification after an initial research-grade ID has been reached?

(Not sure what decisions were made in 2018.)

@johnvanbreda : is there anything else you need to know, such as the CNC project names or codes on iNaturalist?

**Comment by MNSmith** [comment]
From a Verification point of view, getting a "Research Grade" ID on iNaturalist requires at least two people to suggests / agree with a name.  This gives rise to 2 potential problems:  

1) Species in "unpopular" groups may only get 1 suggestion, or it may take some time for a record to get a second agreement.  Given that the Nature Challenge is a time limited event then it would seem sensible to get records over into iRecord asap rather than them trickling in over time.

2) iNaturalist IDs are crowdsourced, so overall IDs can and do change.  If the ID changes, how would impact on record transfer?

Given that any incoming iNaturalist records will be going onto the Verification grid as a new record, and that they should be treated the same by a Verifier as any other incoming record, I would like to see these records come in as soon as they can.  Just bring across the original name the iNat record was input with.

Will there be any feedback to iNats if the record on iRecord ends up with a different name? 

Any plans to do this with iSpot records?

**Comment by DavidHepper** [comment]
This raises several questions and suggestions:
- It appears that iRecord isn't being used as the primary verification tool for these records so why not only import those that have already received two agreeing ID suggestions? This reduces the risk of importing records that are subsequently redetermined.
- When imported, the _sample:survey_reference_code_ (set to "iNaturalist") and _occurrence:external_key_ (set to the record's unique key in iNaturalist) should be included for traceability.
- Feeding back name changes from iR to iN could be a Phase 2 enhancement.
- iSpot seems to me a different animal and I wouldn't support importing from it. 
- Observation.org would be a much more useful source than iSpot. Competent Dutch naturalists - who seem to disperse along with most of their compatriots in migratory swarms each summer - use it for recording in their target holiday destination, including dark corners of the UK.

**Comment by johnvanbreda** [comment]
From the technical perspective, importing all records or just research grade records is a simple case of adjusting a filter. There are currently 206K records on iNat for the UK of which 121K are research_grade, so not importing other records will miss some in the long run as well as slowing down the flow during the event. Having said that, is slowing down the flow during the event such a bad thing?

Picking up on David's first bullet point I'm not sure we should consider the iNat agreements system the same as verification - just a handy initial screening of the record.

On the second point - the records will be imported into a website/survey dataset that is specific to iNat data so they are easily recognisable.

My main concerns with this whole process as it stands are:

* Our experts will invest effort in verifying the records which will be reset if the records are then changed on iNat. This could be mitigated against by coding it so that verified records are "locked" at our end, or new identifications are just added as comments. We might then need a report which lists records that are verified but not in agreement with the current iNat ID.
* If we use research_grade data only it will skew the dataset away from the tricky to ID but interesting stuff. If we use all data, then the first problem becomes even more acute.
* If we use all data then we risk flooding the verifiers with low grade records which could be frustrating.

**Comment by MNSmith** [comment]
> * iSpot seems to me a different animal and I wouldn't support importing from it.

From my perspective, iNaturalist and iSpot are essentially the same thing, both are sites where identifications are crowdsourced rather than verified.  Both collect the basics of a biological record, who, what, where, when, but by there very nature the identifications attached to them are fluid and open to change, esentially "anyone" can change the determination of a record.

iRecord is different in that the records are Verified.  While records can be redetermined there is much more control over the process, both in terms of how it is done and the management of the process.  Biological records can float between all of these various systems for as long as they like, but at some point the Recording Scheme or Verifier managing a particular group of records has to say somewhere along the line "Final Answer".  I think iRecord should be that place.

I've not come across the Observation.org system, though my first thought is "not another one".  iSpot has a huge stockpile of potentially useful biological records that are nearly all UK based that really should be properly verified via iRecord.

I think we should be treating all of these other systems as additional data collection and collation systems in the same way we have the iRecord app or other Indicia type forms and pages.  Once they arrive in iRecord then whatever happens to the record in the orignating system is of no concern to us, although some sort of feedback / identification confirmation - mismatch might be useful to them.   Verifiers will only need to concern themselves with what happens in iRecord, not elsewhere.  The record is imported once, and once only.

What sorts of record volume for UK records are we talking about coming from iNats, and should we not be pushing iRecord more as the preferred system for things like this?  As for "low grade records", that would be no different from the variety of records we see at present from things like Bioblitzes.

**Comment by johnvanbreda** [comment]
I think the difference between iSpot and iNaturalist is that iSpot was originally intended as a learning resource for ID skills rather than a record collection resource. I'm not sure the users are aware of that distinction or if it still applies.

iNaturalist has ~ 200K records in the UK. Whilst I understand the point about pushing iRecord, iNat is being used internationally for the City Nature Challenge and it did not make sense to the organisers to be different here - hence the need for a data flow.

I agree with the notion about the verifier decision being the final answer. I think a sensible way forward is therefore to allow all UK based iNaturalist records into iRecord and to continue updating changes from iNaturalist into iRecord for records whilst they remain as pending review. Once a record has been accepted by an iRecord verifier, we stop overwriting it with changes from iNaturalist. At some point we could build a tool for looking for discrepancies where an iNaturalist record has had further suggestions after the verification event but I don't think this is a priority.

@kitenetter you'll need to assess if you agree and let me know.

**Comment by kitenetter** [comment]
@johnvanbreda I suggest we proceed as follows, and review how things have gone later in the year:
- We only import research grade observations
- If determinations change, or other edits are made, at the iNat end, we re-import and reset to 'pending review'

We don't take action on these at the moment:
- As far as I can see, we don't need to filter to species level or better, because iNat only allows research grade to be reached if a species-level or better ID is agreed
- No need to implement a 'stop overwriting' procedure following verification - let's see how often things do actually get overwritten following verification, and if it happens too frequently we can implement a 'stop overwriting' procedure at a later stage

All these decisions can be revisited following a review later in the year, when we will have a better idea of the scale of the exercise, and any issues that have arisen. And indeed whether the exercise has been worthwhile at all in producing good data.

Two questions:

1. Photos in iNat can have a variety of CC licences, and I believe we are able to import and display the licence, but iNat users can choose to revoke the CC licence altogether - are we able to exclude such photos from our import?
2. What happens if an iNat observation reaches research grade and is imported into iRecord, but subsequently falls out of research grade at the iNat end (which can happen for a variety of reason including redetermination to a higher taxon level)? If we are only importing research grade records, does this mean that records that move back out of research grade will not be subsequently recognised as 'edits' to a previously imported record, and thus will not get re-imported and updated within iRecord? If so we may have to live with that, but it would be good to know what the situation is.

Ideally there could be some return dialogue from iRecord to iNaturalist, but we don't currently have the resources to tackle that.

In principle we could investigate links with iSpot and Observation.org but that is also not something we can tackle at the moment.

When we discussed this with City Nature Challenge they were proposing to encourage their local naturalists to engage with the iNat review process in order to get observations into the research grade category if appropriate, and I will remind them of the value in doing that.

**Comment by DavidHepper** [comment]
This looks like a good and practical plan to me.
- Please confirm that records will arrive in iRecord as Unverified.
- Will the species ID suggest/agreement history in iNat be preserved in iRecord?
- Records should have a visible External Key from iNat, for traceability, unlike UKBMS records, for example.

**Comment by DavidRoy** [comment]
@DavidHepper to correct one thing in your comment:
"Records should have a visible External Key from iNat, for traceability, unlike UKBMS records, for example."
UKBMS uses the same Indicia data warehouse as iRecord so the ID is as shown

**Comment by kitenetter** [comment]
@DavidHepper I can confirm that records will arrive as unverified. I don't think we can store the ID history in iRecord.

@johnvanbreda I assume we are importing the iNat record_id into the iRecord external key, but can we make that visible to verifiers? One way of doing this would be to have an "external URL" attribute which would include the iNat record_id, and display this to verifiers so that they can click through to the original observation on iNat if required. That would be good to do if at all possible.

**Comment by DavidHepper** [comment]
Excellent news, thanks, @DavidRoy:
> UKBMS uses the same Indicia data warehouse as iRecord so the ID is as shown

**Comment by johnvanbreda** [comment]
Picking up the questions above:
1. Unlicensed iNat photos are no longer imported by our code.
2. If a record reaches research grade, gets imported, then falls out of research grade again, then we will not update it. The original "research grade" record remains in iRecord.
3. iNat records will indeed arrive as unverified records. 
4. We won't maintain the iNat agreement/ID history in iRecord, but will retain a link to the record. 
5. As #4 - we maintain the iNat record ID in a field called external_key.
6. The external key will indeed appear on the verification details page as one of the "Key facts".

**Comment by kitenetter** [comment]
Will the 'key facts' external ID be clickable to go back to the observation on iNaturalist? I'm guessing not. It would be a nice enhancement to add that feature but not a priority.

Will close once we have checked that the imports are happening and the data is appearing correctly.

**Comment by johnvanbreda** [comment]
In the ES version of verification, you get a button to click to take you to the iNat record details page.

**Comment by MNSmith** [comment]
Ok - found the button to go to iNats.  For some reason I was expecting a link to be hightlighted in the Record details pane.

**Comment by johnvanbreda** [comment]
@BirenRathod The remaining task before this can be closed is to set up the scheduled task to import iNat data. I think this could be done once a day?

**Comment by BirenRathod** [comment]
@DavidRoy & @johnvanbreda 

I have setup the scheduled task to run import every night.

**Comment by johnvanbreda** [comment]
@BirenRathod The task failed last night. I think this is because the services part of the URL should go into the parameter ("services/rest_api_sync"), rather in than the actual command after the index.php bit. Also it should maybe call via https?

**Comment by BirenRathod** [comment]
@johnvanbreda 
I have implemented the scheduled task. It should work tomorrow hopefully.

**Comment by johnvanbreda** [comment]
Sorry @BirenRathod this didn't work again. Looking at the task which calls scheduled_tasks (and works) it looks like you should be calling the index.php file directly rather than via http. Also the services/rest_api_sync part then needs to go in a separate parameter.

If I run the following from the command line then it works (replace PHPPATH with the correct path as I think it's best not to give out any details like this on a public forum):
```
PHPPATH\php.exe "D:\websites\warehouse\index.php" "services/rest_api_sync"
```

I've set up the task to do the above, but it still fails to run if I right click and run it immediately. I'm not sure why - there is nothing in the server log.

**Comment by BirenRathod** [comment]
@johnvanbreda 

Thanks John for making those changes. I just made small changes like putting "/" and removed it back. After those change, I run the task scheduler again and it runs without any error generated. Again, I can't see anything in the log, so I can't see whether it has run successfully or not.

**Comment by johnvanbreda** [comment]
@BirenRathod are you sure the settings saved correctly? If I right click and run the task it still fails.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Yes, It runs under my credential fine. So, I have changed the credential of the scheduled task, so should be fine running under any credential.

**Comment by johnvanbreda** [comment]
Thanks Biren
