### ISSUE TITLE
Elastic Search Index not updating

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#802]
It looks like the ES index has not been added to since 18th Feb.  This is tagged as urgent as it affects verifiers (and many other things)

**Comment by kitenetter** [comment]
There are also least some problems with records that have been re-exposed from the UKBMS following the removal of the auto-verification. Here is an example for bee-flies - none of these records are currently visible on the ES page:

![image](https://user-images.githubusercontent.com/16039111/75025561-56b74b00-5493-11ea-8755-5326d4ecbbb3.png)

**Comment by DavidHepper** [comment]
Could there be some system-generated alert for this and a procedure for response? The indexer is so fundamental to ES Verify. It's not the first time it has failed for several days.

**Comment by johnvanbreda** [comment]
The Logstash import had got stuck because of an error, but I've not yet located the error in any logs. @DavidHepper - good idea, I will try and implement an alert email.

@kitenetter I checked a couple of these Bee Fly records. The first is not yet indexed due to this issue, but I found 6683782 ad 3161014, masquerading as you, as long as I set the status filter to All Records.

**Comment by kitenetter** [comment]
It looks like there is a different issue for the UKBMS records.

On the old verification page, they are flagged as follows:
- Record status is Not reviewed
- There is no verification comment
- There is no verification flag

On the new verification page, they are flagged as follows:
- They should be available from the "Pending" view, but aren't, and can only be found by filtering for All records
- There is no verification comment
- There is a "considered correct" icon against the records in the right-hand details pane - this should not be there

The original record page view shows the record status as "Awaiting review", e.g.:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=7026725

Does this mean that the update applied in #486 still has some loose ends?

**Comment by johnvanbreda** [comment]
@kitenetter as far as I can tell from the audit log, that record was correctly indexed into ES as a verified record as it was auto-verified on 3rd Jan 2019, but was subsequently reset to pending review and it is this change that has not been indexed. There is a deleted occurrence comment relating to the verification, so I suspect it was auto verified in mistake, indexed into ES, then undone. We are now waiting for ES indexing to catch up and it should be then correct in both systems.

**Comment by burkmarr** [comment]
Yes that was one of the records incorrectly auto-accepted by the auto-verifier which I reverted at the backend of last year and marked the comment as deleted (https://github.com/BiologicalRecordsCentre/iRecord/issues/692#issuecomment-551011497). Did I miss doing something that would have triggered Logstash to pick up the change?

**Comment by johnvanbreda** [comment]
No, it should have been automatic.

@BirenRathod I'm trying to use Logstash to email me when it logs an error, using the same settings as on warehouse1 for SMTP. I get an SMTP authentication error 554, which means the mail was rejected. Is there a way I can find out why?

**Comment by BirenRathod** [comment]
@johnvanbreda 
Well, if logtash means this is elastic server you are talking about, so it hasn't configured to send any emails. I will configure it and let you know.

**Comment by johnvanbreda** [comment]
Have checked the indexing over the weekend as I applied a few optimisations to the reports on Friday. Seems to have been fine, so will remove the urgent tag but leave open till I manage to get Logstash to send emails on errors.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Have you already configured email setting somewhere? as you mentioned you have used same settings as warehouse1.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I found your setting in one of conf file. I implemented your settings. see if that works ok.

**Comment by johnvanbreda** [comment]
Thanks - the settings were in occurrences-http-indicia.conf in the Logstash-config folder. I'm trying it now but it may take a while for another error.

**Comment by BirenRathod** [comment]
Yes, that is the one I have amended.

**Comment by kitenetter** [comment]
I'm still seeing small numbers of UKBMS records on my old verification page that have not appeared on the new. There are now fewer of them than shown in the screenshot at the top of this issue but there are still some there.

**Comment by johnvanbreda** [comment]
I've checked my, yours and the Syrphid records and they all look correct now, so closing.
