### ISSUE TITLE
iRecord Drupal 9 website

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#980]
Following discussions this morning we agreed that it would be sensible to explore implementing a Drupal 9 version of iRecord, since the step from 8 to 9 is a small one. Has implications for related libraries and PHP.

@BirenRathod to investigate using iForms in Drupal 9.

**Comment by BirenRathod** [comment]
@johnvanbreda As I mentioned, I have installed the module but it does produces some bug which is expected and suggests, it does require implementation to work with Drupal 9.

Drupal\Component\Serialization\Exception\InvalidDataTypeException: drupal-9/modules/custom/iform/iform.routing.yml: Duplicate key "iform.joingroup" detected at line 53 (near " _permission: 'access content'"). in Drupal\Core\Discovery\YamlDiscovery->decode() (line 24 of drupal-9\core\lib\Drupal\Core\Discovery\YamlDiscovery.php).

**Comment by johnvanbreda** [comment]
I'm about to try another D9 installation so will get back to you on this.

**Comment by BirenRathod** [comment]
I also found this link from Pantheon which is useful to implement D8 code to D9. Not many changes required.
https://pantheon.io/docs/drupal-9#can-i-upgrade-my-existing-drupal-site-to-drupal-9

**Comment by johnvanbreda** [comment]
It turned out to be quite a lot of work as I had to convert lots of jQuery UI code which is no longer easily supported. I've now managed to get it working though haven't tested all functionality.

To use Drupal 9 you need:
* Iform module running the feature-d9 branch.
* Client_helpers folder running the feature-d9 branch.
* Media folder running the feature-d9 branch.
* Indicia_features running the feature-d9 branch.
* Warehouse running the develop.

The feature-d9 branches can all be merged back into the main branches once tested as the changes are all compatible with D8 & D9.

There are lots of changes in the above branches which will need testing:
* Convert from jQuery.ui.datepicker to HTML 5 date inputs. This involves a completely new control for inputting dates when vague dates are enabled.
* Switch to FancyBox version 3.
* Convert from jQuery.ui.dialog to using Fancybox as a dialog control (via the helper method $.fancyDialog which I added).
* Lots of stuff relating to non-standard media fixed (e.g. adding links to Twitter, Soundcloud, videos etc), because whilst converting to D9 and FancyBox 3 I found bugs that needed to be sorted. This includes standardising the way that licence data is shown on image popups.
* Convert from $.sortable to the Sortable class now used by Drupal.

Additionally:
* You can now authenticate as a website for Elasticsearch, avoiding the need to set up lots of aliases and configuration for each separate website.

Note that I've removed deprecated Drupal 8 code from all the core stuff, but not project specific forms since I don't want to introduce bugs that I can't easily test for, so they will need some work when migrating sites to Drupal 9 (e.g. NPMS, UKBMS).

Over to you @BirenRathod !

**Comment by BirenRathod** [comment]
Thanks for @johnvanbreda. Really appreciated. I will test on my machine and let you know. 

I think project specific should more concern to Andy & Gary as they need to test & make sure its functionality.

**Comment by BirenRathod** [comment]
@johnvanbreda 
This is my initial assessments about iForm Drupal 9. Here is the URL - > http://test.brc.ac.uk/irecord9/
- Installation & enabling module fine.
- iForm settings done fine.
-  I created form to add list of records where I found jquery.datepicker error in firefox debug panel. Layout is at present problem but that is due to date jquery problem. 
I will do further testing once this resolved. Password is the same as live site.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I have added the reference in libraries for missing jquery datepicker and it works fine now. Also, it resolved the layout issue too.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Some more....
1. jQuery error from taxa_search.php although it did get list of species.
2. Can't upload photo. below is the error message from jquery.
$(...).progressbar is not a function
3. Without photo record submitted fine.

**Comment by johnvanbreda** [comment]
We are trying to move away from jQuery.ui so adding the reference to the ui.datepicker library is not the right approach. Looking at the code, the old datepicker is still referenced from a few project specific forms which will need to be replaced. I noticed it was also referenced from the lock icon code which I missed so converting that to support the HTML 5 date input is a task to do.
Are you sure you are using feature-d9 on the media library? It should use an HTML5 progress element now rather than jQuery UI.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I know you don't want to use jquery datepicker but I seen other references of jquery and It will allow me to test further, so I added but it is in feature-d9, so you can just ignore when you merge the code in the master. i didn't as in library in media repository it is just referenced in the iform.libraries.yml and install the datepicker module.

**Comment by BirenRathod** [comment]
@johnvanbreda  yes I'm sure it is using feature-d9 media library.

**Comment by BirenRathod** [comment]
@johnvanbreda Sorry my mistake, I checked media & client_helpers folder again and founf the settings was not right. So no amendment needed for date picker. 

But photo upload problem still there. it is not showing jquery but just html error & also error from taxa_search.php file.

**Comment by BirenRathod** [comment]
@johnvanbreda Although my mistake of adding datepicker jquery has solved most jquery problems. That was not expected. 
After I removed datepicker jquery, now tab is not working and throws error. so that is another one to look.

**Comment by BirenRathod** [comment]
I think you need to remove the jquery datepicker validator and add individual validator for HTML 5 date.

**Comment by johnvanbreda** [comment]
@BirenRathod please can you post details of the jQuery.ui.datepicker error as well as the one in taxa_search.php as I'm not seeing those problems.

**Comment by BirenRathod** [comment]
@johnvanbreda you can see on the test site which I setup here test.brc.ac.uk/irecord9

**Comment by BirenRathod** [comment]
@johnvanbreda you will error in debug panel not on the page.

**Comment by BirenRathod** [comment]
@johnvanbreda if you can't find below are the errors. Ignore my message about taxa_search.php that may be not clearing cache.
1. Uncaught TypeError: indiciaData.dateFormat is undefined
2. Uncaught TypeError: $.validator.methods[method] is undefined
3. Photo upload html error.

**Comment by johnvanbreda** [comment]
I think the first 2 errors are fixed if you pull the latest code. For error 3, this works on my local machine but you are getting ERR_CONNECTION_RESET. You will need to debug whether the request is reaching upload.php or not.

**Comment by BirenRathod** [comment]
@johnvanbreda Thanks for those changes you made.
After that, I installed iform on my machine and it works fine. 
Then I pulled the code on test but it was not working. I uninstalled it and reinstall everything and it works fine. I think that was due to not clearing cookies on browser.

Just small issue I found but this is not urgent. When I uninstalled and reinstalled iform & easy login module, it didn't uninstall completely all fields from the database even though there are no values stored in the database. I know this problem already exists in Drupal 8.

**Comment by BirenRathod** [comment]
also photo upload doesn't work if site setup as subsite which is why it didn't work on test.brc.ac.uk/irecord.

**Comment by BirenRathod** [comment]
@johnvanbreda & @DavidRoy 
Everything works fine, so we could go ahead with Drupal 9 for iRecord. 

@johnvanbreda If you can pass me some more info about indicia block, would be good.

**Comment by johnvanbreda** [comment]
Please pull the feature-d9 branches for client_helpers and the indicia_features folders. The Indicia blocks module just gives you 2 simple blocks to add to the home page - one with a list of records, the other with a map. You can set up a home page as a basic page, then use the Layout Builder module. Set the Display settings for the Basic Page content type to use Layout Builder and to allow each page to have it's own layout. Then your home page will have a "Layout" tab that lets you create a layout and add blocks.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Thanks for this details. I already pulled those branches when I pulled the iform. I can see those two blocks in the blocks list too and I'm aware of layout settings too. My question was regarding configuration in the block, like using URL or anything... but from your above details, it should be straight setup. So I will give it a go.

**Comment by BirenRathod** [comment]
@johnvanbreda, @DavidRoy, @kitenetter & @burkmarr 

I have now migrated the irecord Drupal 7 to Drupal 9, below is the link. 
http://test.brc.ac.uk/irecord9/

@johnvanbreda - There is no verification 3 or 4 in Drupal 9, so I replaced them with verification 5. I haven't tested yet but that I will do next.
- Recent records & photo block haven't created yet, which I will do next soon.

If you find any problem or missing let me know. I will make above changes in couple of days but it is ready to test. You can submit record in training mode as it is link to live warehouse.

**Comment by johnvanbreda** [comment]
@BirenRathod thanks. Which pages required verification 3 or 4? I thought that we've been using Verification 5 or the new Elasticsearch code for a long while now.

Apart from the missing home page, when I log in as myself, the menu has lots of missing stuff, e.g. the links to the standard enter a list of records or enter a casual records forms. If I reconstruct the expected URL for the enter a casual record form then I get an access denied.

I noticed that the HTML5 date control doesn't have the form-control class so looks wrong on Bootstrap - I will fix this in the code.

I also found that the Edit page for my account has lots of bits missing, I can't select my location, taxon groups, or enable vague date entry for example.

**Comment by BirenRathod** [comment]
@johnvanbreda 
If you look at noe is -> 9, 470, 3186 have got verification 3 & 470 has got verification 4.

some of links in menu need to sort out the permission bit, which I will do soon. 

Yes, I have hidden for time being on "My account", which I will sort out soon too.

**Comment by johnvanbreda** [comment]
Here's the commit to add the class to the date picker for Bootstrap: https://github.com/Indicia-Team/client_helpers/commit/8dd5288b19f569c9f51f290f3df2049ae48eb3d0

Node 470 is old, hopefully unused. I think it can be deleted.

I could not find a node 3186, but 3188 is the current "old verification" page on the menu and that is using verification 5.

**Comment by BirenRathod** [comment]
@johnvanbreda 
- I have pulled the code of date picker.
- I implemented the permissions of all menu links.

**Comment by johnvanbreda** [comment]
Thanks - that looks better.

* My Records page gives an Elasticsearch error.
* Lots of the less-frequently used recording forms are missing, e.g. the ones I tried from https://www.brc.ac.uk/irecord/moors-for-future/ring-ouzel-redwing-postcard work on iRecord but not the new site.

**Comment by BirenRathod** [comment]
@johnvanbreda 

- My records page works fine for me, no error.
- moors for future gives below error 
- rror: Call to undefined function l() in extension_misc_extensions::breadcrumb() (line 298 of D:\websites\drupal9\modules\custom\iform\client_helpers\prebuilt_forms\extensions\misc_extensions.php)

#0 D:\websites\drupal9\modules\custom\iform\client_helpers\prebuilt_forms\includes\dynamic.php(694): extension_misc_extensions::breadcrumb(Array, Array, NULL, Array, '/irecord9/moors...', Array)

**Comment by DavidRoy** [comment]
@BirenRathod 

- My records page gives me an error when logged in as /user/2
- All records gives the same error
- Verify menu also gives the same error
- Record menu is missing the main data entry forms and the taxon forms.
- Activities lacking images under 'actions' column
- Activity summary gives error, 
 e.g. http://test.brc.ac.uk/irecord9/activities/summary?group_id=1826&implicit=f
 http://test.brc.ac.uk/irecord9/activities/explore?group_id=957&implicit=

**Comment by BirenRathod** [comment]
@DavidRoy 

All issues have been resolved now except the last one which needs to change the code in theme file. I will let you about it soon.

**Comment by johnvanbreda** [comment]
@BirenRathod some more issues for you:
* Logged in as myself, http://test.brc.ac.uk/irecord9/my-records works now, but shows over 400,000 records (rather than approx 4000).
* The record details page crashes, e.g. http://test.brc.ac.uk/irecord9/record-details?occurrence_id=19399350.
* Moors for the future record forms links still broken - e.g. http://test.brc.ac.uk/irecord/moors-for-future/hare-postcard - I just realised this is because the URL is wrong (irecord rather than irecord9).

**Comment by BirenRathod** [comment]
@johnvanbreda 
- One of the problem of seeing all those records is the permission. The permissions are not setup same as Drupal 7 of iForm. 
- yes on test site, I setup with irecord9. let me see if easy to fix.

**Comment by BirenRathod** [comment]
@johnvanbreda 
- I have implemented the URL now, it is test.brc.ac.uk/irecord and moors form is fine to load. 
- This record-details?occurrence_id=19399350 page is not loading on live which could be the same problem on test too.
As I mentioned before there are some permission implications on most of the forms because indicia iform permissions are not same as live irecord one. 
@johnvanbreda can you look at please? specially records loaded in my records and other pages.

**Comment by BirenRathod** [comment]
@johnvanbreda more about permission...
If I don't enabled the 'authenticated user' permission of 'Access Indicia Iform web pages' then you will see error of elastic search  and don't see any record & can't get access of data entry form & taxon based entry form which David has mentioned above.

**Comment by johnvanbreda** [comment]
"Access Indicia Iform web pages" is the main permission required for any Indicia forms and reports so should be granted to anonymouse and authenticated users. There is a similar "Access iform" permission which is caused by the migration of pages which refer to this permission by name in their settings. As long as they both have the same settings it won't matter.

I rebuilt the content permissions which fixed a few things. 

I also removed the Masquerade block from the bottom of all pages except home, since the autocomplete clashes with ours. 

Some more problems - the login and logout system seems broken. For example, if I'm logged in as admin, then I log out, when I try to log in again it is still logged in as admin. The logout link doesn't work properly. Also, if I am logged in, then the home page still has a login link in the menu. I think it is basically broken because the links are toggling me between irecord and irecord9 in the URL - until this is sorted I don't think I can work on the other issues.

**Comment by BirenRathod** [comment]
@johnvanbreda 
Both "Access Indicia Iform web pages" & "Access iForm" have got same permissions.

- I don't experience of logout & login porblems. Did your tabs mix up with irecord & irecord9?

**Comment by DavidRoy** [comment]
@BirenRathod the site is giving a '404 - File or directory not found.' error for me today
http://test.brc.ac.uk/irecord9/

**Comment by BirenRathod** [comment]
@DavidRoy 
Yes, because URL has changed now. It is now test.brc.ac.uk/irecord

**Comment by johnvanbreda** [comment]
I think there were some cached links, which caused the problems with login/logout - they seem to have gone now.

On the Explore My Records page, at the top of the form structure there is supposed to be the following:
```
<input type="hidden" class="es-filter-param" data-es-bool-clause="must" data-es-field="metadata.created_by_id" data-es-query-type="term" value="{{ indicia_user_id }}" />
```

This is the hidden input that filters all requests to the logged in user's data. But, on the Drupal 9 development site it looks like this:
```
<input type="hidden" class="es-filter-param" data-es-bool-clause="must" data-es-field="metadata.created_by_id" data-es-query-type="term" value="" />
```

The token `{{ indicia_user_id }}` is missing. If I edit the page and add it back, then save it, the save does not "take" and the page is still unfiltered. Something is stripping this token out. I have a local D8 test setup and a local D9 test setup and I can reproduce this problem on Drupal 9 but not Drupal 8 so it must be new. I guess it relates to the token looking like a twig replacement.

**Comment by johnvanbreda** [comment]
I've managed to confirm the problem with {{ indicia_user_id }} is not saving, as it is correct in the database, but loading. I'm looking into this now.

**Comment by johnvanbreda** [comment]
@BirenRathod I've just pushed an update to the iform module develop branch which fixes the problem I found above.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I updated the code from develop branch. Clear cache and reload the 'My records' page, don't see any impact. Am I missing anything?

**Comment by BirenRathod** [comment]
@johnvanbreda After I added {{ indicia_user_id }}, it works nicely.

**Comment by johnvanbreda** [comment]
I think the {{ indicia_user_id }} value needed to be resaved into the code - it's now working though my personal My Records page is showing an odd set of records which I'm looking into.

**Comment by johnvanbreda** [comment]
Minor thing - https://www.brc.ac.uk/irecord/explore/nhm-wlg shows a full width report, the equivalent on the dev site is narrow.

Activity summaries seem to be broken - http://test.brc.ac.uk/irecord/simple-activity-summary?group_id=1325&implicit=f

Also, I don't know why but on my user account, My Records shows > 4000 records for iRecord live, but only 80 records for iRecord dev site of which some aren't mine. The request looks the same though (using browser dev tools and the Network tab) so I can't see why, as they are pointing to the same server.

**Comment by BirenRathod** [comment]
@johnvanbreda 

This page http://test.brc.ac.uk/irecord/simple-activity-summary?group_id=1325&implicit=f throws error, like this one Error: Call to undefined function variable_get() in irecord_preprocess_page() (line 30 of D:\websites\drupal9\themes\custom\irecord\irecord.theme) 

basically it needs a value of indicia_website_id and indicia_password.

**Comment by johnvanbreda** [comment]
Presumably the theme is not on Github so you will have to fix this yourself. If you look elsewhere for calls to iform_get_connection_details() you will see how to do it.

**Comment by BirenRathod** [comment]
@johnvanbreda Thanks for the suggestion. That is what exactly, I was expecting from you. I have resolved that now. Although theme file is already on pantheon but no need to bother now.

**Comment by johnvanbreda** [comment]
@BirenRathod thanks - the activity summary works now, although it needs to be styled correctly as it looks like the CSS has not been applied.

**Comment by BirenRathod** [comment]
@johnvanbreda Actually the whole site needs to styling, so will do next.

**Comment by BirenRathod** [comment]
@DavidRoy We need indicia_api module to work with Drupal 9. At present this modules already got Drupal 8 implementations.
@burkmarr We need indicia_license module to comply with Drupal 9. This module is in Drupal 7, so need to implement in Drupal 9.

**Comment by johnvanbreda** [comment]
@BirenRathod I will run the upgrade_status module on the indicia_api module now and fix errors it finds so it's ready for Drupal 9. I don't have a quick way of testing it so that will need to be done afterwards.

**Comment by johnvanbreda** [comment]
@BirenRathod @kazlauskis can you confirm which branch of the indicia_api I should be updating ready for Drupal 9 please?

**Comment by BirenRathod** [comment]
@kazlauskis please perform a test once @johnvanbreda will finish migrating a module.

**Comment by kazlauskis** [comment]
In the end, we will need both of the modules installed on iRecord but the priority should be to support any existing apps which only use the `v1` branch functionality at the moment. So I suggest doing the `v1` for now.

**Comment by johnvanbreda** [comment]
@BirenRathod I've updated both v1 and v2 branches now so you can copy the code to iRecord d9.

**Comment by BirenRathod** [comment]
@johnvanbreda I will do it soon.

**Comment by BirenRathod** [comment]
@kazlauskis Indicia_Api module has downloaded and enabled now. Ready to test.

**Comment by BirenRathod** [comment]
@johnvanbreda I have added the recent sightings & map block. I don't think, that is the home page to expect to see. So one of the confusion I got which I didn't clear in my previous query was the parameter text editor appears in block settings. So what parameter shall I use to configure this block or these blocks?

**Comment by kazlauskis** [comment]
@BirenRathod sure, is there a specific deadline to test the Indicia API module?

**Comment by DavidRoy** [comment]
@kazlauskis not as urgent as the butterfly and FIT Count apps ;-)

**Comment by johnvanbreda** [comment]
@BirenRathod I don't think those blocks have any configuration. Perhaps they need a config form to enable filtering by the user's taxon group and location preferences. Or you could make new blocks in this module that use the same old code from the iRecord home page (even better, if Elasticsearch ;)).

One other thing - the develop branch of the Indicia user UI options module is now Drupal 9 compatible. You will need that to enable turning vague dates on and off in the user's profile settings.

**Comment by DavidRoy** [comment]
@BirenRathod the home page should only use ElasticSearch reports.  The whole of the Drupal 9 site should use ElasticSearch reports where they are available

**Comment by BirenRathod** [comment]
@johnvanbreda I thought you have already included an Elasticsearch in indicia blocks module.

**Comment by BirenRathod** [comment]
@johnvanbreda Also, I have created the map block using your indicia block. The only change I did is that I use osm layer. You can see home page on Chrome. despite using osm layer, the map is still getting Google map service layer in the background. Do you know, why? 

I think this could be one of the reason of using Google map service on live iRecord in the background which David queried in this #891

**Comment by BirenRathod** [comment]
@johnvanbreda I have installed Indicia User UI options module now. Installation fine but while setting up fields in the account give an below error. 
Error from -> http://test.brc.ac.uk/irecord/admin/config/people/accounts/form-display
Error -> Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 150 of D:\websites\drupal9\core\lib\Drupal\Core\Entity\EntityTypeManager.php).

http://test.brc.ac.uk/irecord/admin/config/people/accounts/form-display
--
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 150 of D:\websites\drupal9\core\lib\Drupal\Core\Entity\EntityTypeManager.php).


http://test.brc.ac.uk/irecord/admin/config/people/accounts/form-display
--
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 150 of D:\websites\drupal9\core\lib\Drupal\Core\Entity\EntityTypeManager.php).

**Comment by johnvanbreda** [comment]
@BirenRathod -
1. I could not reproduce any problem in the Indicia User UI options module or accessing the list of fields when it is installed.
2. In the develop branch of the code, I've done significant work to make any Google layers only load the API when they are genuinely accessed rather than on page load (see #891).
3. In the Indicia Blocks module, there are now 3 blocks for Elasticsearch data outputs - Recent Records, Recent Records Map and Totals. You can combine all 3 to make the iRecord home page.

Also - for the home page, please use the Layout Builder module with the option set to override the layout for individual pages of content type "Basic Page" and use this to set up the home page layout. This will be much easier than using the Structure > Blocks page to add all the blocks for every page then restricting the pages they appear on. I think it is best practice now to only put blocks which appear on all pages (or at least a large number of pages) on the Structure > Blocks configuration.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda
1. Yes, I realised that that is due to not properly setup fields in accounts fields settings. 
2. yes, I seen on #891, 
3. is this on develop branch?

Yes, I will use Layout builder once I will get proper results.

**Comment by johnvanbreda** [comment]
3. Sorry - I committed to the wrong branch. Now sorted.

**Comment by BirenRathod** [comment]
Thanks for that @johnvanbreda.
I found error straight after I implemented the block to display map. You can see javascript error in Chrome or Firefox developer tools.

**Comment by johnvanbreda** [comment]
@BirenRathod I think these blocks work on a page managed by layout builder, but not as standard blocks. Although we should fix this, I don't have time to do that at the moment.

**Comment by DavidRoy** [comment]
@johnvanbreda @BirenRathod thanks for your work to get this site migrated.  We can leave this now for another month as there are other more urgent projects in March

**Comment by BirenRathod** [comment]
@johnvanbreda I implemented all those forms the suggestion you made in #812. I noticed one of the parameter @limitDynamicAttrsTaxonGroupIds=[133] is not present on irecord live. did you miss it or is it for new website?

Also, I have added layout builder to the home page now. I also added elastic search block. I have configured those blocks to visible only for authenticated users. I still need to configure for display records of irecord. if you could send me configuration, I will implement those blocks.

**Comment by BirenRathod** [comment]
@DavidRoy, @johnvanbreda & @burkmarr 
One of thing I mentioned in the discussion the module developed by Rich is iform_licenses. It is not implemented for Drupal 9. So @johnvanbreda we need that.

**Comment by burkmarr** [comment]
I modifed the module most recently to make some small changes, e.g. to warn if media license not selected, but @johnvanbreda developed it originally.

**Comment by BirenRathod** [comment]
Thanks @burkmarr. @johnvanbreda once you update that, let me know.

**Comment by johnvanbreda** [comment]
@BirenRathod I've added the Drupal 8 iform_licences module to the develop branch.

**Comment by BirenRathod** [comment]
Thanks, @johnvanbreda. I pulled the code and it is now available on test.

**Comment by johnvanbreda** [comment]
@BirenRathod OK, that looks like it is working, thanks. 

For the blocks on the home page, I've now fixed an issue causing them to not populate, due to the caching of JavaScript. But, I notice that you've modified the module code to add an access check. Your code hard-codes the block to only appear if logged in, which I think might not always be desirable (especially as this block library might expand to include other blocks). We could do a couple of things:
1. Add a permission field to each block's config page, so the permission required to view the block can be controlled.
2. Just use the block access module (https://www.drupal.org/project/block_access) to control access.

Do you have a preference?

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, I have added the access check temporarily to see if it works ok.

I have just enabled block_access module and I don't see viewing permission for indicia block unless I missed anything. So in that you can permission field to each block's config page.

**Comment by johnvanbreda** [comment]
@BirenRathod the Block Access module didn't seem to do what I expected, so you can remove it. I've now updated the blocks so they have a config option allowing you to set a permission name that the user must have in order to see the block.

**Comment by BirenRathod** [comment]
@johnvanbreda I removed the block_access module and pulled the code now, so you can see permission name text editor.

**Comment by BirenRathod** [comment]
@johnvanbreda 
also, this http://test.brc.ac.uk/irecord/admin/reports/dblog/event/355 error keep generating due to bug in iform user ui. You can see logs in Drupal's "Recent log messages" related to that. If you could implement that would be good, so I can upload module on Pantheon site.

**Comment by johnvanbreda** [comment]
@BirenRathod I've fixed that plus 1 other log message. You need to pull both the iform module and indicia_features.

**Comment by BirenRathod** [comment]
Many thanks @johnvanbreda.  I pulled the code now.

**Comment by BirenRathod** [comment]
@johnvanbreda You can now stop using test.brc.ac.uk/irecord and start using the Pantheon one. Here is the URL -> https://test-brc-irecord.pantheonsite.io/ 

Currently below things to resolve ....

- [ ] 1. There is bug in location shp importor module, this is the log link -> https://dev-brc-irecord.pantheonsite.io/admin/reports/dblog/event/9

- [ ] 2. I don't see any options in drop down list or checkboxes in user profile for species groups, Recording location, None of them in Verification section, 

- [ ] 3. Block permission doesn't work after added the permission name.

- [ ] 4. What filter shall I use in "Recent records" and "Recent map", so it will display record like current iRecord site.

**Comment by johnvanbreda** [comment]
1. I have fixed this but note that there is no need for the Locations SHP importer module to be installed on iRecord. It's for another project, though may be useful in future.
2. I thought that we were thinking about dropping the options for setting your taxon groups and recording location in the user profile, as the filters system is much more powerful and useful. We have definitely stopped using this approach for verification so I think those profile fields can be deleted. We need to check with @kitenetter and @DavidRoy - at the moment the code to fill in the options for these controls has not been ported to Drupal 8.

Will look at the other 2 issues in a moment.

**Comment by BirenRathod** [comment]
@johnvanbreda 
1. I have updated code and disabled the module now.
2. @kitenetter  & @DavidRoy , please check it and let me know, so I can delete those fields.

Let me know @johnvanbreda for 3 & 4 as soon as you get chance.

**Comment by BirenRathod** [comment]
@johnvanbreda 
For iRecord point of view only this iform_remote_download module needs drupal 8 compatibility code. after that most work done on iRecord Drupal 9.

**Comment by johnvanbreda** [comment]
4. - I've added a sort to the recent records block to bring the most recently added records to the top.

Still looking at 3 as it works locally but not on the dev site.

**Comment by johnvanbreda** [comment]
3. Fixed by resaving the block config on the layout manager. I don't know why but when the blockAccess method was requesting the block config, it was getting a different version to elsewhere with the view_permission parameter set to an empty string.

**Comment by BirenRathod** [comment]
@johnvanbreda
3. did you resave on test or dev website? 
4 .I have updated the code, so I can see latest records. What shall we do in terms of getting same display to home page as current live site. Although, I don't know that is still desire to achieve on new site.

**Comment by BirenRathod** [comment]
@johnvanbreda 
3. I resave on test too. It works now.

**Comment by johnvanbreda** [comment]
@BirenRathod thanks - I only saved on dev. 

I don't think that we were going to spend effort trying to make the home page display's identical, as the one on iRecord is very old and could do with a refresh.

**Comment by BirenRathod** [comment]
@johnvanbreda I have no problem with that. I think it should be a fresh one.

I have also resolved most of the style or display related issues. you can see on test site. Although there is one found which needs implement in the code if possible. 
This is the page link -> https://test-brc-irecord.pantheonsite.io/irecord-app-summary
If you click on Trending tab, you will see all the photos are not same size as current website. one option is you can add col-sm-2 class with 'thumbnail' class and may be restricting size of div for all texts.

**Comment by johnvanbreda** [comment]
If you pull the code again, I've changed the summary photos to use the new cardGallery control. Can you try and see if that looks OK?
The totals on the first tab could do with some styling.

**Comment by BirenRathod** [comment]
@johnvanbreda I have pulled the code now and update on pantheon now. Although, I hove done this, I hope you could do this on your own as you have got an access of Pantheon site.

**Comment by BirenRathod** [comment]
@johnvanbreda I missed to mentioned that, it looks much better now.

**Comment by johnvanbreda** [comment]
@biren the Pantheon Drupal 9 site does not have the iform_user_ui_options folder file contents from live iRecord. This means you cannot enable vague date mode on date controls. What is the correct way to place the files on the server please?

**Comment by BirenRathod** [comment]
@johnvanbreda First of all you have tag a wrong guy biren (I didn't put `@` sign here, this belongs to biren ghandhi not me) It is @BirenRathod. Second I generally upload through SFTP using Cyburduck if there are lots of files. If it is one or two file, I can upload through this link -> https://test-brc-irecord.pantheonsite.io/media/add/document

**Comment by johnvanbreda** [comment]
Ah - sorry - normally I get an autocomplete for your full tag! 
Do you just SFTP to the dev site then use Pantheon to copy the files over?

**Comment by BirenRathod** [comment]
@johnvanbreda you can do sftp of test site as well. I recon because we use now test site, please do sftp of test site.

**Comment by johnvanbreda** [comment]
@BirenRathod I've uploaded the files.

**Comment by BirenRathod** [comment]
@johnvanbreda By using SFTP means , you don't need to put site into sftp mode. Just use the SFTP connection to upload files on iRecord dev, test or live site on Pantheon.

**Comment by kitenetter** [comment]
@DavidRoy @kitenetter to do some initial testing before inviting external users to test
@BirenRathod to continue transferring content onto new site

**Comment by BirenRathod** [comment]
@johnvanbreda I have implemented the site and added block on the home page. 
To achieve exact format of display like current iRecord, I need to setup  three blocks 
Before login
1. "Recent records (with photos)" 
After login
2. "Recent sightings" 
3. "Recent photos"

Can you there fore guide me? how can we achieve this?

**Comment by BirenRathod** [comment]
@johnvanbreda jQuery support for date picker missed to include in the latest released. Please do so.

**Comment by johnvanbreda** [comment]
I'll get back to the blocks - but jQuery datepicker is no longer used by Indicia.

**Comment by BirenRathod** [comment]
@johnvanbreda I have updated code now. but there is still need update for date notification which occurred after date entered. See below screenshot. 
![image](https://user-images.githubusercontent.com/5941255/122764265-38d04500-d297-11eb-807b-c99fff4f0ebe.png)

**Comment by BirenRathod** [comment]
@johnvanbreda the changes you made for this irecord-app-summary page has not been released in the master branch too.

**Comment by BirenRathod** [comment]
@johnvanbreda Ignore my comment about irecord-app-summary page. it is there, it just took longer to appeared for some reason.

**Comment by BirenRathod** [comment]
@johnvanbreda I found this error for record-details page when page has got social media links.
TypeError: Argument 2 passed to Drupal\Component\Plugin\PluginManagerBase::createInstance() must be of the type array, string given, called in /code/web/modules/custom/iform/client_helpers/prebuilt_forms/record_details_2.php on line 841 in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 71 of /code/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php)

#0 /code/web/modules/custom/iform/client_helpers/prebuilt_forms/record_details_2.php(841): Drupal\Component\Plugin\PluginManagerBase->createInstance(NULL, 'addtoany_button')

**Comment by BirenRathod** [comment]
I have updated styles across the site. I have also updated all the contents. I will updated all users at the time of putting on live. 
@kitenetter & @DavidRoy Site is ready to test once @johnvanbreda make changes for blocks.

@johnvanbreda Below changes require
1. The error message above for social media icon needed for record details page.
    e.g. https://test-brc-irecord.pantheonsite.io/record-details?occurrence_id=20727678
2. The blocks added for "Recent records" & "Recent sightings" are just an example. It needs changes, so it should exactly get results like live current website.
3.  "Recent photos" block needed to add once user logged in.
4. Records on map doesn't exactly same as live site, so please check that too.
5. As I mentioned before, fields appear in the user accounts like "Species groups", "Recording location" etc... You mentioned @DavidRoy needs to decide whether we keeping or not. If we are then the values appear in that needs a code implementation.  if not I will delete those.

Anything else let me know. I'm keep updating contents, which take more times. This will get worse if we take longer to act as number of users growing too. So if we need to decide an make this live sooner then later.

**Comment by johnvanbreda** [comment]
I've fixed point 1 - the social media icons on record details.

**Comment by johnvanbreda** [comment]
Blocks updated as per today's discussion. The recent records is filtered to verified records only.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. That left to last option to look into it but @kitenetter can start testing the site.

**Comment by johnvanbreda** [comment]
@BirenRathod the theme settings on iRecord contain a custom CSS textbox. I don't think these CSS rules are applied in the new iRecord theme but they should be. For example, on the activities page, an activity that is linked to the iRecord app should show an icon next to the activity title.

**Comment by BirenRathod** [comment]
@johnvanbreda No, they don't because it is not a same theme. but icon display is not a problem on a new site.

**Comment by johnvanbreda** [comment]
Go to https://www.brc.ac.uk/irecord/activities/list, then search for BLS and you will see the title "BLS lichen records" has a mobile phone icon next to it. This is functionality that is added via the Custom CSS box on Appearance > Settings > iRecord. These CSS rules need to be copied into the new theme then as part of the migration task:
```css
table.report-grid h3.enter-app-record, table.report-grid h3.enter-app-record-list {
    background: url("/irecord/sites/default/files/images/mobile.png") no-repeat left center;
    padding-left: 24px;
}
.page-join .app-link, .page-node-824 .app-link {
  background: url("/irecord/sites/default/files/images/mobile.png") no-repeat left center;
  padding-left: 30px;
}
.page-join .enter-app-record, .page-node-824 .enter-app-record, .page-join .enter-app-record-list, .page-node-824 .enter-app-record-list {
  display: none;
}
.button.enter-app-record, .button.enter-app-record-list {
  display: none;
}
```

There may be other rules in the Custom CSS box that are also useful.

**Comment by BirenRathod** [comment]
@johnvanbreda I have added above rules now. There may be but I can't confirm if they needed, so if you or @kitenetter found anything missing let me know and I will add it.

**Comment by BirenRathod** [comment]
@johnvanbreda I found that in client_helpers directory lot of forms still uses deprecated db_query function (e.g. report_calendar_smmary.php & ..._summary2.php) . I have only mentioned two but there are 8 files. Now this may be important or not for iRecord but these needs to replace with \Drupal::database()->query function.

**Comment by johnvanbreda** [comment]
@BirenRathod agreed, but they are all project specific and not on iRecord. It would be better for the updates to be done as part of the relevant projects.

**Comment by BirenRathod** [comment]
@johnvanbreda I know some are project specific but may be not all. Anyway I leave that to you.

**Comment by BirenRathod** [comment]
@johnvanbreda Also, for me it is difficult to do for project basis as I have migrated all Drupal 8 sites to Drupal 9 now, so easy to implement at once place and use it from there.

**Comment by DavidRoy** [comment]
@kitenetter can we close this issue now?
